services:
  text2sql-app:
    build: .
    container_name: text2sql_app
    ports:
      - "8502:8501"
    environment:
      OLLAMA_HOST: http://ollama:11434
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: employee_insight
    volumes:
      - "C:/DDrive/MyWorkspace/Data Science/LLM+POC/text+to+sql+rag+llm:/app"
    working_dir: /app
    command: streamlit run app.py
    depends_on:
      - ollama
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
      - ./pull-model.sh:/pull-model.sh
    entrypoint: ["/bin/sh", "/pull-model.sh"]  
    restart: always

volumes:
  ollama_models: